export const categoryList = [
    'Nessuna',
    'Abbigliamento',
    'Alimentari e cura della casa',
    'Usato',
    'App e giochi',
    'Audiolibri',
    'Auto e moto - Parti e accessori',
    'Bellezza',
    'Buoni Regalo',
    'Cancelleria e prodotti per ufficio',
    'Casa e cucina',
    'CD e vinili',
    'Elettronica',
    'Fai da te',
    'Film e tv',
    'Giardino e giardinaggio',
    'Giochi e giocattoli',
    'Gioielli',
    'Grandi elettrodomestici',
    'Handmade',
    'Illuminazione',
    'Industria e scienza',
    'Informatica',
    'Kindle Store',
    'Libri',
    'Meno di 10 €',
    'Moda',
    'Musica digitale',
    'Orologi',
    'Prima infanzia',
    'Prodotti per animali domestici',
    'Salute e cura della persona',
    'Scarpe e borse',
    'Software',
    'Sport e tempo libero',
    'Strumenti musicali e DJ',
    'Valigeria',
    'Videogiochi'
];

export const getCategoryName = (id) => categoryList[id];
export const getCategoryID = (name) => categoryList.indexOf(name);